#########
#
# workshop-template-b, evanwill
# https://github.com/evanwill/workshop-template-b
# A Jekyll template for a simple workshop website
#
#########

# Site settings
# title appears in the header
title: "UNISTRA-DS-2020: Intro to Network Analysis and NLP"
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Font Awesome 5 free, https://fontawesome.com/icons?d=gallery&m=free
# some options: fas fa-wrench; fas fa-cogs; fas fa-code; fas fa-chalkboard-teacher; fas fa-book-open
title-icon: fas project-diagram
# description, keywords, and image for meta tags
description: "Blended Learning Module: Intro to network analysis and natural language processing"
keywords: "network analyais, language processing, python, R, graphs, topic modelling, text analysi"
featured-image: "/images/uidaho-workshop.jpg"

# author settings for cc-by, appears in the footer and credits
author: Daniel Hain & Roman Jurowetzki
pub_year: 2021
github_username: SDS-AAU

# add the full url for the github repository
repo: "https://github.com/SDS-AAU/UNISTRA-DS-2021"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https://SDS-AAU.github.io/
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: /UNISTRA-DS-2021

# add search box to footer?
search: true

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
# Build settings
markdown: kramdown
